# Generated by Django 5.2.4 on 2025-08-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
